<?php
namespace Ksfraser\Amortizations\Services;
use Ksfraser\Amortizations\Models\Loan;
class ComplianceReportingService {
    public function generateTRIDDisclosure(Loan $loan): array { $m = $this->calculateMonthlyPayment($loan->getPrincipal(), $loan->getAnnualRate() / 12, $loan->getMonths()); $t = ($m * $loan->getMonths()) - $loan->getPrincipal(); return ["loan_amount" => $loan->getPrincipal(), "interest_rate" => $loan->getAnnualRate(), "monthly_payment" => round($m, 2), "total_interest" => round($t, 2), "total_amount" => round($loan->getPrincipal() + $t, 2), "number_of_payments" => $loan->getMonths()]; }
    public function generateAPRDisclosure(Loan $loan): array { $a = $loan->getAnnualRate(); $m = $this->calculateMonthlyPayment($loan->getPrincipal(), $a / 12, $loan->getMonths()); return ["annual_percentage_rate" => $a, "finance_charge" => round(($m * $loan->getMonths()) - $loan->getPrincipal(), 2), "amount_financed" => $loan->getPrincipal(), "total_of_payments" => round($m * $loan->getMonths(), 2)]; }
    public function generatePaymentScheduleDisclosure(Loan $loan): array { $r = $loan->getAnnualRate() / 12; $m = $this->calculateMonthlyPayment($loan->getPrincipal(), $r, $loan->getMonths()); $s = []; $b = $loan->getPrincipal(); for ($i = 1; $i <= 12 && $i <= $loan->getMonths(); $i++) { $in = round($b * $r, 2); $p = round($m - $in, 2); $b = round($b - $p, 2); $s[] = ["payment_number" => $i, "payment_amount" => round($m, 2), "principal" => $p, "interest" => $in, "balance" => max(0, $b)]; } return ["payment_schedule" => $s, "disclosure_type" => "TRID Compliant"]; }
    public function validateTRIDCompliance(Loan $loan): array { $is = []; if ($loan->getPrincipal() <= 0) $is[] = "Invalid principal"; if ($loan->getAnnualRate() < 0) $is[] = "Invalid rate"; if ($loan->getMonths() < 1) $is[] = "Invalid term"; return ["compliant" => empty($is), "issues" => $is, "compliance_date" => date("Y-m-d")]; }
    public function generateRegulatoryNotice(Loan $loan, string $type): array { return ["notice_type" => $type, "loan_id" => $loan->getId(), "generated_date" => date("Y-m-d"), "content" => "Notice: $type"]; }
    public function calculateAPYFromAPR(Loan $loan): float { $a = $loan->getAnnualRate(); return pow(1 + ($a / 12), 12) - 1; }
    public function generateComplianceReport(Loan $loan): array { $t = $this->validateTRIDCompliance($loan); return ["loan_id" => $loan->getId(), "compliance_checks" => ["trid_compliant" => $t["compliant"], "apr_disclosed" => true, "terms_clear" => true], "disclosures" => ["trid" => $this->generateTRIDDisclosure($loan), "apr" => $this->generateAPRDisclosure($loan)], "generated_date" => date("Y-m-d H:i:s")]; }
    public function exportComplianceDocumentation(Loan $loan): string { return json_encode($this->generateComplianceReport($loan), JSON_PRETTY_PRINT); }
    private function calculateMonthlyPayment(float $p, float $r, int $n): float { if ($r == 0) return $p / $n; return $p * ($r * pow(1 + $r, $n)) / (pow(1 + $r, $n) - 1); }
}